### ISSUE TITLE
How to load initial image from assets folder

### ISSUE THREAD

**Issue by MartinMbae** [JulioCGMC/image_picker_widget#1]
Thank you for this great package. 
I am try to pass an initial image from my assets as
                    initialImage: File("assets/images/logo.png"),
but I'm getting an error  "Invalid argument(s): No host specified in URI file:///assets/images/logo.png"
What is the right way of doing it.

**Comment by JulioCGMC** [comment]
Hy, sorry for the delay, i'm not sure how to make the asset file a File type but, to make this easier: now initialImage accepts not only File and String, but also ImageProvider type, so now you can send AssetImage(src)

It's on the 1.0.3 release. 

Thanks for the feedback.
