### ISSUE TITLE
Crop Function

### ISSUE THREAD

**Issue by aiman97adzhar** [JulioCGMC/image_picker_widget#2]
Hello sir, can you please add crop function? or is there ways to do it already?

**Comment by JulioCGMC** [comment]
Hi, well, at the moment there is no way to crop or resize the image, but it looks like a good implementation and will be available in the next version of this pack later this day.

**Comment by JulioCGMC** [comment]
Inserted the option, hope it suits you:

https://pub.dev/packages/image_picker_widget/versions/2.0.2

**Comment by aiman97adzhar** [comment]
That was fast, Thank you very much.
