### ISSUE TITLE
Function InitialImage as Asset Image

### ISSUE THREAD

**Issue by aiman97adzhar** [JulioCGMC/image_picker_widget#3]
Hello sir, can you update one more option to pick asset image as InitialImage? Thank you

DecorationImage? _image() {
    if (image is ImageProvider) {
      return DecorationImage(image: image, fit: BoxFit.cover);
    }
    if (image is File)
      return DecorationImage(image: FileImage(image), fit: BoxFit.cover);
    else if (image != null && image.toString().isNotEmpty)
      return DecorationImage(image:Networkmage(image.toString()), fit: BoxFit.cover);  <<Need as Asset Image
    return null;
  }

**Comment by aiman97adzhar** [comment]
initialImage: File("assets/image/profile_placeholder.jpeg"),

Added: File at front

**Comment by JulioCGMC** [comment]
Hello, actually right now you already can send a asset image, it just need to be an ImageProvider, so you need to send'it as Flutter demands, like bellow: 

AssetImage("assets/image/profile_placeholder.jpeg", ..otherParams);

The File() is for device locationed files, not project locationed, for those you use AssetImage() [Which extends ImageProvider] or Image.asset() [Which is of type Image()]

That was already a issue: https://github.com/JulioCGMC/image_picker_widget/issues/1

**Comment by JulioCGMC** [comment]
For more info: https://docs.flutter.dev/development/ui/assets-and-images
