### ISSUE TITLE
Upload to server

### ISSUE THREAD

**Issue by AimanKyo97** [JulioCGMC/image_picker_widget#4]
How to post local image to server? I try but getting Image broken

**Comment by JulioCGMC** [comment]
Could you send more details about that?
Because in my tests i've uploaded the file with FirebaseStorage or using base64 format from the response of _onChange_, as example bellow:

`onChange: (file) {
    if (file != null) {
       var url = await _bucketStorage.uploadFile(file, path: "images/${user!.id}/profile_image");
       if (url != null && userData != null) {
         userData!.profileImage = url;
       }
   }
}`

**Comment by AimanKyo97** [comment]
I have try the code but I got :

<Code>EntityTooLarge</Code>
<Code>Your proposed upload exceeds the maximum allowed size</Code>
<Code>ProposedSize - 165 |  MaxSizeAllowed - 114</Code>

How to made the file modify the size?

I almost there now, thanks you brother.

**Comment by AimanKyo97** [comment]
Here is the example .. 14 KB is working one and bytes got broken

<img width="821" alt="Screenshot at Feb 15 16-42-44" src="https://user-images.githubusercontent.com/67236402/154024921-f153ed32-7616-4d19-a32e-bd5293e26176.png">

**Comment by aiman97adzhar** [comment]
I have checked it and it need to change quality to 80, how can i do that?

**Comment by JulioCGMC** [comment]
So, i have done something similar and have used a cropped package, i'll send one here:
https://pub.dev/packages/image_cropper
Use the `compressQuality` attribute.

**Comment by JulioCGMC** [comment]
Wish i could help more, but the ideia of the package was to be more like a widget with some help on functionality, but nothing too heavy.

**Comment by aiman97adzhar** [comment]
In image picker got function for add quality after the pick, can you add that function? only that missing

**Comment by JulioCGMC** [comment]
Hello, I have added this function and it is available in version 2.0.3, too, I recommend you to check associated image crop functions added in version 2.0.2
